Repository MIT-Emerging-Talent/ET6-foundations-group-16, pull requests merged in 2025-01, with the labels that each got.

#23 Contributing readme
  CONTRIBUTING.md
Labels: documentation

#45 Add calc_avg.py in the solutions README
  solutions/README.md
Labels: documentation

#46 Calculate Average challenge
  solutions/calculate_average.py
  solutions/tests/test_calculate_average.py
Labels: challenges

#24 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#47 Add Matrix Spiral Traversal Solution and Tests + README Update
  solutions/README.md
  solutions/spiral_traverse.py
  solutions/tests/test_spiral_traverse.py
Labels: challenges

#50 Update README.md
  solutions/README.md
Labels: documentation

#56 UPDATE - learning goals
  collaboration/learning_goals.md
Labels: documentation

#68 clarify "no function calls" item
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#78 Communication markdown Set up
  collaboration/communication.md
Labels: documentation

#77 Decimal to binary
  solutions/decimal_to_binary.py
  solutions/password_strength.py
  solutions/tests/test_decimal_to_binary.py
  solutions/tests/test_password_strength.py
Labels: challenges

#80 Add is_palindrome function with unit tests
  solutions/is_palindrome.py
  solutions/tests/test_is_palindrome.py
Labels: challenges

#81 Mohamed's availability
  collaboration/communication.md
Labels: documentation

#52 solution for the simple calculator challenge
  solutions/simple_calculator.py
  solutions/tests/test_simple_claculator.py
Labels: challenges

#71 Reverse string solution
  solutions/reverse_string.py
  solutions/tests/test_reverse_string.py
Labels: challenges

#67 Finalize the contributing file
  CONTRIBUTING.md
Labels: documentation

#91 Fix CI check related to grading_system.py
  solutions/grading_system.py
Labels: enhancement

#98 Implement Kronecker Product Function
  solutions/README.md
  solutions/kronecker_product.py
  solutions/tests/test_kronecker_product.py
Labels: challenges

#72 Greatest number challenge
  solutions/greatest_number.py
  solutions/tests/test_greatest_number.py
Labels: challenges

#106 Feet to meters
  solutions/feet_to_meters.py
  solutions/tests/test_feet_to_meters.py
Labels: challenges

#108 Update feet to meters
  solutions/README.md
  solutions/feet_to_meters.py
Labels: challenges

#75 Direction to degree
  solutions/README.md
  solutions/direction_to_degree.py
  solutions/tests/test_direction_to_degree.py
Labels: challenges

#111 Volts to amperes
  solutions/tests/test_volts_to_amperes.py
  solutions/volts_to_amperes.py
Labels: challenges

#95 password
  solutions/password_strength.py
  solutions/tests/test_password_strength.py
Labels: challenges

#117 adding my solution file name
  solutions/README.md
Labels: documentation

#113 Miles to kilometers
  solutions/README.md
  solutions/miles_to_kilometers.py
  solutions/tests/test_miles_to_kilometers.py
Labels: challenges

#133 Notes readme
  notes/README.md
Labels: documentation

#130 Area of Circle & multiply number
  collaboration/communication.md
  solutions/README.md
  solutions/area_circle.py
  solutions/multiplication.py
  solutions/tests/test_area_circle.py
  solutions/tests/test_multiplication.py
Labels: challenges

#137 fix CI in communication.md
  collaboration/communication.md
Labels: documentation

#138 Solutionnew
  solutions/README.md
Labels: documentation

#126 Solution for (common elements) challenge
  solutions/README.md
  solutions/common_elements.py
  solutions/tests/test_common_elements.py
Labels: challenges

#127 Contributing update
  collaboration/communication.md
  collaboration/learning_goals.md
Labels: documentation

#139 fix bug in test_direction_to_degree
  solutions/tests/test_direction_to_degree.py
Labels: enhancement

#140 Fix feet to meters
  solutions/tests/test_feet_to_meters.py
Labels: enhancement

#141 Fix mile to kilometers
  solutions/tests/test_miles_to_kilometers.py
Labels: enhancement

#142 Fix volts to amperes
  solutions/tests/test_volts_to_amperes.py
Labels: enhancement

#143 readme update in solutions
  solutions/README.md
Labels: documentation

#145 This is the project retrospective
  collaboration/retrospective.md
Labels: documentation

#135 Returns the longest word in that sentence
  solutions/longest_word.py
  solutions/tests/test_longest_word.py
Labels: challenges

#148 Fibonacci Sequence Generator Challenge
  solutions/fibonacci.py
  solutions/tests/test_fibonacci.py
Labels: challenges

#150 Update README.md
  solutions/README.md
Labels: documentation

#146 Added GCD Calculator Challenge
  solutions/README.md
  solutions/gcd.py
  solutions/tests/test_gcd.py
Labels: challenges

#153 Revert "Add is_positive function with unit tests"
  solutions/is_positive.py
  solutions/tests/test_is_positive.py
Labels: bug

#154 Add is_positive function with unit tests
  solutions/is_positive.py
  solutions/tests/test_is_positive.py
Labels: challenges

#156 Modify some points in the retrospective file
  collaboration/retrospective.md
Labels: documentation

#155 fix codes files
  solutions/direction_to_degree.py
  solutions/feet_to_meters.py
  solutions/miles_to_kilometers.py
  solutions/volts_to_amperes.py
Labels: enhancement, challenges

#152 add solution to Count Character challenge and updated README
  solutions/README.md
  solutions/count_character.py
  solutions/tests/test_count_character.py
Labels: challenges
